import '../domain/models/goal_categories.dart';
import '../domain/models/goal_enums.dart';
import '../domain/models/goal_template.dart';

/// Popular goal presets — each maps to existing editor fields only.
const List<GoalTemplate> goalTemplates = [
  GoalTemplate(
    id: 'study',
    label: 'Study',
    emoji: '📚',
    suggestedTitle: 'Study daily',
    categoryId: GoalCategories.study,
    repeatCadence: GoalRepeatCadence.daily,
    measurement: MeasurementKind.sessions,
    targetValue: 1,
    intensity: 3,
    reminderEnabled: true,
    reminderMinutesFromMidnight: 20 * 60,
    setupSteps: [
      'Block study time on calendar',
      'Gather materials',
      'Review last session notes',
    ],
  ),
  GoalTemplate(
    id: 'fitness',
    label: 'Fitness',
    emoji: '🏃',
    suggestedTitle: 'Stay active',
    categoryId: GoalCategories.fitness,
    repeatCadence: GoalRepeatCadence.weekly,
    measurement: MeasurementKind.sessions,
    targetValue: 4,
    intensity: 4,
    reminderEnabled: true,
    reminderMinutesFromMidnight: 7 * 60,
    setupSteps: ['Pick workout days', 'Prepare gear', 'Set a warm-up routine'],
  ),
  GoalTemplate(
    id: 'learn_skill',
    label: 'Learn Skill',
    emoji: '🧠',
    suggestedTitle: 'Learn a new skill',
    categoryId: GoalCategories.study,
    repeatCadence: GoalRepeatCadence.daily,
    measurement: MeasurementKind.sessions,
    targetValue: 1,
    intensity: 3,
    setupSteps: [
      'Choose a course or resource',
      'Install required tools',
      'Schedule first practice block',
    ],
  ),
  GoalTemplate(
    id: 'read_books',
    label: 'Read Books',
    emoji: '📖',
    suggestedTitle: 'Read more books',
    categoryId: GoalCategories.habits,
    // One-time outcome goal: chapters accumulate over the whole period.
    repeatCadence: GoalRepeatCadence.off,
    measurement: MeasurementKind.custom,
    targetValue: 20,
    intensity: 2,
    customLabel: 'chapters',
    setupSteps: [
      'Pick your next book',
      'Keep it visible',
      'Set a daily reading window',
    ],
  ),
  GoalTemplate(
    id: 'focus',
    label: 'Deep Work',
    emoji: '🎯',
    suggestedTitle: 'Deep work sessions',
    categoryId: GoalCategories.focus,
    repeatCadence: GoalRepeatCadence.weekly,
    measurement: MeasurementKind.minutes,
    targetValue: 300,
    intensity: 4,
    reminderEnabled: true,
    reminderMinutesFromMidnight: 9 * 60,
    setupSteps: [
      'Research deep work protocols',
      'Silence notifications',
      'Define your focus block',
    ],
  ),
  // ── First-goal picker templates (onboarding handoff, 2026-09-25) ────────
  // Two per interest that had none. Reachable from the first-goal picker's
  // interest filter; the everyday New goal mosaic keeps its five cards.
  GoalTemplate(
    id: 'first_version',
    label: 'First version',
    emoji: '🚀',
    suggestedTitle: 'Build my first version',
    categoryId: GoalCategories.productivity,
    repeatCadence: GoalRepeatCadence.off,
    measurement: MeasurementKind.custom,
    targetValue: 5,
    intensity: 4,
    customLabel: 'milestones',
    setupSteps: [
      'Write down the one problem it solves',
      'List the three features it can\'t ship without',
      'Sketch the first screen or flow',
      'Set a date for a rough first version',
    ],
  ),
  GoalTemplate(
    id: 'first_customers',
    label: 'First customers',
    emoji: '🤝',
    suggestedTitle: 'Get my first 10 customers',
    categoryId: GoalCategories.productivity,
    repeatCadence: GoalRepeatCadence.off,
    measurement: MeasurementKind.count,
    targetValue: 10,
    intensity: 4,
    customLabel: 'customers',
    setupSteps: [
      'Describe who it\'s for in one sentence',
      'List 20 people or places to reach',
      'Write a short message you can send today',
    ],
  ),
  GoalTemplate(
    id: 'side_income',
    label: 'Side income',
    emoji: '💸',
    suggestedTitle: 'Build a side income',
    categoryId: GoalCategories.productivity,
    repeatCadence: GoalRepeatCadence.weekly,
    measurement: MeasurementKind.sessions,
    targetValue: 3,
    intensity: 3,
    setupSteps: [
      'Pick one skill or thing you can sell',
      'Set a price',
      'Tell three people this week',
    ],
  ),
  GoalTemplate(
    id: 'money_checkin',
    label: 'Money check-in',
    emoji: '📊',
    suggestedTitle: 'Know where my money goes',
    categoryId: GoalCategories.productivity,
    repeatCadence: GoalRepeatCadence.daily,
    measurement: MeasurementKind.sessions,
    targetValue: 1,
    intensity: 2,
    reminderEnabled: true,
    reminderMinutesFromMidnight: 21 * 60,
    setupSteps: [
      'Pick one place to note spending',
      'Write down today\'s spending',
      'Review every Sunday',
    ],
  ),
  GoalTemplate(
    id: 'brain_dump',
    label: 'Brain dump',
    emoji: '🗂️',
    suggestedTitle: 'Get everything out of my head',
    categoryId: GoalCategories.productivity,
    repeatCadence: GoalRepeatCadence.daily,
    measurement: MeasurementKind.sessions,
    targetValue: 1,
    intensity: 2,
    reminderEnabled: true,
    reminderMinutesFromMidnight: 20 * 60,
    setupSteps: [
      'Write down everything on your mind',
      'Sort into today, this week, later',
      'Pick tomorrow\'s three',
    ],
  ),
  GoalTemplate(
    id: 'clear_space',
    label: 'Clear space',
    emoji: '🧹',
    suggestedTitle: 'Declutter one space a week',
    categoryId: GoalCategories.productivity,
    repeatCadence: GoalRepeatCadence.weekly,
    measurement: MeasurementKind.sessions,
    targetValue: 1,
    intensity: 2,
    setupSteps: [
      'List the spaces that bother you most',
      'Start with the smallest',
      'Set a 20-minute timer',
    ],
  ),
  GoalTemplate(
    id: 'morning_start',
    label: 'Morning start',
    emoji: '🌅',
    suggestedTitle: 'Start my day on purpose',
    categoryId: GoalCategories.focus,
    repeatCadence: GoalRepeatCadence.daily,
    measurement: MeasurementKind.sessions,
    targetValue: 1,
    intensity: 3,
    reminderEnabled: true,
    reminderMinutesFromMidnight: 7 * 60,
    setupSteps: [
      'Pick a wake-up time you can keep',
      'Decide the first thing you\'ll do',
      'Put your phone out of reach at night',
    ],
  ),
  GoalTemplate(
    id: 'focused_hour',
    label: 'Focused hour',
    emoji: '⏱️',
    suggestedTitle: 'One focused hour a day',
    categoryId: GoalCategories.focus,
    repeatCadence: GoalRepeatCadence.daily,
    measurement: MeasurementKind.minutes,
    targetValue: 60,
    intensity: 3,
    reminderEnabled: true,
    reminderMinutesFromMidnight: 9 * 60,
    setupSteps: [
      'Choose the hour',
      'Silence notifications',
      'Decide what the hour is for the night before',
    ],
  ),
  GoalTemplate(id: 'custom', label: 'Custom Goal', emoji: '✨'),
];

GoalTemplate? goalTemplateById(String id) {
  for (final t in goalTemplates) {
    if (t.id == id) return t;
  }
  return null;
}
