import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../thinking/application/reflection_parser.dart';

/// Day-scoped store for the strategist's reminder proposals (FR-R-61).
///
/// SharedPreferences, deliberately: proposals are one day's advisory prose —
/// they are regenerated by tomorrow's pass, must not replicate to other
/// devices, and losing them costs one suggestion. That is preference-grade
/// data, not entity-grade; the full local-first set would be ceremony.
///
/// D7 is structural here: nothing that reads this store can mutate anything.
/// A proposal's only affordance is a pre-drafted Coach message the user must
/// send themselves, at which point the coach's normal tool machinery — with
/// its confirmation and its 30-minute undo — takes over.
class StrategistProposalsStore {
  static const _kPrefsKey = 'reminder_strategist_proposals_v1';

  Future<void> saveForDay(
    String dayKey,
    List<ReminderStrategyProposal> proposals,
  ) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(
        _kPrefsKey,
        jsonEncode({
          'day': dayKey,
          'items': [for (final p in proposals) p.toMap()],
        }),
      );
    } catch (e) {
      debugPrint('[Strategist] store failed: $e');
    }
  }

  /// Today's proposals, or empty — a stale day reads as nothing.
  Future<List<ReminderStrategyProposal>> loadForDay(String dayKey) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final raw = prefs.getString(_kPrefsKey);
      if (raw == null) return const [];
      final decoded = jsonDecode(raw);
      if (decoded is! Map<String, dynamic>) return const [];
      if (decoded['day'] != dayKey) return const [];
      final items = decoded['items'];
      if (items is! List) return const [];
      return [
        for (final raw in items)
          if (raw is Map<String, dynamic>)
            if (ReminderStrategyProposal.fromMap(raw) case final p?) p,
      ];
    } catch (e) {
      debugPrint('[Strategist] load failed: $e');
      return const [];
    }
  }
}
